// this is a silly solution
// just to show you how different
// components of this framework work
// please bring your wise to write
// a 'real' solution :)

#include <iostream>
#include <cstdio>
#include <fstream>
#include <string>
#include <cstring>
#include <dirent.h>
#include <json/json.h>

void real();
void readjson(std::ifstream &ifile);

int main() {
    std::cout << "call real()" << std::endl;
    real();
    return 0;
    std::string cheat_src =
"// this is supposed to be generated by codegen tool\n\
#include \"../run.h\"\n\
\n\
void kernel_example(float (&B)[32][16], float (&C)[32][16], float (&A)[32][16]) {\n\
    for (int i = 0; i < 32; ++i) {\n\
        for (int j = 0; j < 16; ++j) {\n\
            A[i][j] = B[i][j] * C[i][j];\n\
        }\n\
    }\n\
}";
    std::ofstream ofile("./kernels/kernel_example.cc", std::ios::out);
    ofile << cheat_src;
    ofile.close();
    return 0;
}

void real(){
    //std::cout << "Try to open directory PROJ_ROOT_DIR/project1/cases" << std::endl;

    DIR *dir;
    struct  dirent *ent;
    if ((dir = opendir ("./cases")) != NULL) {
        /* print all the files and directories within directory */
        while ((ent = readdir (dir)) != NULL) {
            char jsonfilename[256] = "./cases/";
            if(strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name,"..") == 0)
                continue;
            strcat(jsonfilename, ent->d_name);
            printf ("%s\n", jsonfilename);
            std::ifstream ifile(jsonfilename, std::ios::in);
            readjson(ifile);
        }
        closedir (dir);
    } else {
    /* could not open directory */
        std::cout << "Could not open directory \"cases\"" << std::endl;
        return ;
    }
}

void readjson(std::ifstream &ifile){
    Json::CharReaderBuilder rbuilder;
    rbuilder["collectComments"] = false;
    Json::Value root_group;
    Json::String errs;
    bool parse_ok = Json::parseFromStream(rbuilder, ifile, &root_group, &errs);
    if(!parse_ok){
        std::cout << "Json::parseFromStream  failed!" << std::endl;
        return;
    }
    std::cout << root_group["name"] << std::endl;
    std::cout << root_group["kernel"] << std::endl;
    
}