// this is a silly solution
// just to show you how different
// components of this framework work
// please bring your wise to write
// a 'real' solution :)

#include <iostream>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <cstring>
#include <dirent.h>
#include <json/json.h>

#include "parser.h"
#include "IRVisitor.h"
using std::string;

// debug output
#define VERBOSE

#ifdef VERBOSE
#define dprintf(format, ...) printf(format, ##__VA_ARGS__)
#else
#define dprintf(format, ...)
#endif

void real();
void readjson(std::ifstream &ifile);

int main() {
    std::cout << "call real()" << std::endl;
    real();
    return 0;
    std::string cheat_src =
"// this is supposed to be generated by codegen tool\n\
#include \"../run.h\"\n\
\n\
void kernel_example(float (&B)[32][16], float (&C)[32][16], float (&A)[32][16]) {\n\
    for (int i = 0; i < 32; ++i) {\n\
        for (int j = 0; j < 16; ++j) {\n\
            A[i][j] = B[i][j] * C[i][j];\n\
        }\n\
    }\n\
}";
    std::ofstream ofile("./kernels/kernel_example.cc", std::ios::out);
    ofile << cheat_src;
    ofile.close();
    return 0;
}

void real(){
    //std::cout << "Try to open directory PROJ_ROOT_DIR/project1/cases" << std::endl;

    DIR *dir;
    struct  dirent *ent;
    if ((dir = opendir ("../project1/cases/")) != NULL) {
        /* print all the files and directories within directory */
        while ((ent = readdir (dir)) != NULL) {

            char jsonfilename[256] = "../project1/cases/";
            if(strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name,"..") == 0)
                continue;
            strcat(jsonfilename, ent->d_name);
            printf ("%s\n", jsonfilename);
            std::ifstream ifile(jsonfilename, std::ios::in);
            readjson(ifile);
            // break;
        }
        closedir (dir);
    } else {
    /* could not open directory */
        std::cout << "Could not open directory \"cases\"" << std::endl;
        return ;
    }
}

void readjson(std::ifstream &ifile){
    Json::CharReaderBuilder rbuilder;
    rbuilder["collectComments"] = false;
    Json::Value root_group;
    Json::String errs;
    bool parse_ok = Json::parseFromStream(rbuilder, ifile, &root_group, &errs);
    if(!parse_ok){
        std::cout << "Json::parseFromStream  failed!" << std::endl;
        return;
    }
    std::string name = root_group["name"].asString();
    std::string data_type = root_group["data_type"].asString();
    std::string kernel = root_group["kernel"].asString();
    std::vector<string> insvec;
    std::vector<string> outvec;
    for(auto &insval : root_group["ins"])
        insvec.push_back(insval.asString());
    for(auto &outval : root_group["outs"])
        outvec.push_back(outval.asString());

    Parser psr(name, insvec, outvec, data_type, kernel);
    psr.build_Kernel();
    // Expr tref = psr.parse_RHS("A<4>[k]+B<7,8>[j+1,j+2]");
    
    // parse_P(string("A<16, 32>[i, j] = A<16, 32>[i, j] + alpha<1> * (B<16, 32>[i, k] * C<32, 32>[k, j]); A<16, 32>[i, j] = A<16, 32>[i, j] + beta<1> * D<16, 32>[i, j];"));
}